application: health-hack-app
version: 1
runtime: python
api_version: 1

handlers:

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /javascript
  static_dir: javascript

- url: .*
  script: main.py
